export const FETCH_QUIZES_START = "FETCH_QUIZES_START";
export const FETCH_QUIZES_FINISH = "FETCH_QUIZES_FINISH ";
export const FETCH_QUIZES_ERROR = "FETCH_QUIZES_ERROR";
export const FETCH_QUIZ_SUCCESS = "FETCH_QUIZ_SUCCESS";
export const ANSWER_STATUS = "ANSWER_STATUS";
export const FINISHED_QUIZ = "FINISHED_QUIZ";
export const CHANGE_QUESTION = "CHANGE_QUESTION";
export const RETRY_QUIZ = "RETRY_QUIZ";